# Generated by Django 5.1.4 on 2026-01-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVAdmin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ev_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EVBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carno', models.CharField(max_length=20)),
                ('reserve', models.CharField(max_length=20)),
                ('slot', models.IntegerField()),
                ('cimage', models.CharField(max_length=20)),
                ('mins', models.IntegerField(default=0)),
                ('plan', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rtime', models.CharField(max_length=20)),
                ('etime', models.CharField(max_length=20)),
                ('rdate', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=10)),
                ('charge', models.FloatField(default=0.0)),
                ('chargetime', models.IntegerField(default=0)),
                ('chargemin', models.IntegerField(default=0)),
                ('chargesec', models.IntegerField(default=0)),
                ('chargest', models.IntegerField(default=0)),
                ('paymode', models.CharField(max_length=20)),
                ('payst', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('btime1', models.CharField(max_length=20)),
                ('btime2', models.CharField(max_length=20)),
                ('alertst', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('smsst', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ev_booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EVRegister',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('account', models.CharField(max_length=20)),
                ('card', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=10000)),
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=128)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'ev_register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EVStation',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('stype', models.CharField(max_length=20)),
                ('numcharger', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('landmark', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('distance', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'ev_station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('booking_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_time_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('cancel_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('reschedule_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('charge_completed_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_alert', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=40)),
                ('station_id', models.CharField(max_length=20)),
                ('charging_period', models.CharField(blank=True, max_length=20, null=True)),
                ('charging_amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('station_id', models.CharField(max_length=20)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChargingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('charging_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('charging_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('reschedule_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('reschedule_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('charging_status', models.CharField(blank=True, max_length=20, null=True)),
                ('booking', models.ForeignKey(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='charging.evbooking')),
            ],
            options={
                'db_table': 'charging_history',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evbooking',
            name='uname',
            field=models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.CASCADE, to='charging.evregister'),
        ),
        migrations.CreateModel(
            name='EVSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('station', models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='charging.evstation')),
            ],
            options={
                'db_table': 'ev_slot',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evbooking',
            name='station',
            field=models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='charging.evstation'),
        ),
    ]
