# Generated by Django 5.1.4 on 2026-01-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evstation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
