# Generated by Django 5.1.4 on 2026-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_evstation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charginghistory',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='evslot',
            name='station',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='evstation',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChargingHistory',
        ),
        migrations.DeleteModel(
            name='EVSlot',
        ),
    ]
