# Generated by Django 5.1.4 on 2026-01-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_remove_charginghistory_booking_remove_evslot_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evstation',
            name='last_seen',
        ),
    ]
