# Generated by Django 5.1.4 on 2026-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_remove_evstation_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evstation',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
