# Generated by Django 6.0.3 on 2026-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0005_evstation_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evregister',
            name='green_points',
            field=models.IntegerField(default=0),
        ),
    ]
