# Generated by Django 6.0.3 on 2026-05-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0006_evregister_green_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='evregister',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EVQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_mins', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('station', models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='charging.evstation')),
                ('uname', models.ForeignKey(db_column='uname', on_delete=django.db.models.deletion.CASCADE, to='charging.evregister')),
            ],
            options={
                'db_table': 'ev_queue',
                'managed': True,
            },
        ),
    ]
